### ISSUE TITLE
Error en descripción y nombre del Producto

### ISSUE THREAD

**Issue by juanchireca** [TodoPago/SDK-Java#10]
Estoy usando el API y tanto en producción como en desarrollo, no me toma ni la descripción(CSITPRODUCTDESCRIPTION) ni el nombre(CSITPRODUCTNAME) del producto.

El metódo que estoy utilizando para generar la operación es: sendAuthorizeRequest().

**Comment by drarko** [comment]
Estimado,
¿Que codigo de error esta devolviendo el servicio?

**Comment by juanchireca** [comment]
No me responde ningún.
El problema está en que utilizo la api para generar una operación, luego redirijo a la url del formulario de Todo Pago. Una vez ahí, se muestra el formulario, el cual no muestra lo que les detallo (nombre y descripcion del producto)

**Comment by drarko** [comment]
@juanchireca los datos enviados en los campos mencionados son para control de fraude.
Para el caso de los pagos por API, en el formulario de Todo Pago se muestra el logo del comercio, que puede cargarse a través del Portal o, en su defecto, la imagen de Todo Pago. 

Saludos

**Comment by juanchireca** [comment]
Ok, pero estoy hablando de la descripción y el nombre del producto. Esta información es la que no se muestra.
Si no estoy entendiendo mal, me estas diciendo que por mas que la información se la pase, el formulario no la va a mostrar ¿es correcto esto?

**Comment by drarko** [comment]
Es correcto @juanchireca, esa información no se muestra en el formulario.
Saludos

**Comment by juanchireca** [comment]
Ok, muchas gracias!

Saludos
