### ISSUE TITLE
No aparecen opciones para Pagos en Efectivo

### ISSUE THREAD

**Issue by juanchireca** [TodoPago/SDK-Java#11]
No aparecen opciones para pago en efectivo, me sale el siguiente texto: "Esta operación no admite medios de pago en efectivo."

Probé obtener los medios de pagos mediante el metódo **getVRParameters()** y en el resultado me salia como opción de **Rapi Pago** (ID: 500). Luego lo agregué como opción **parameters.put("AVAILABLEPAYMENTMETHODSIDS", "1#42#500");** y nada.

Tal vez no está habilitada la opción para la API, pero en ningún lado se especifica.

Espero que me puedan ayudar.
Saludos

**Comment by precagno** [comment]
No está habilitada la opción .Saludos.

**Comment by precagno** [comment]
No está habilitada la opción.Saludos.
