### ISSUE TITLE
Nombre del repositorio

### ISSUE THREAD

**Issue by gustavofilippini** [TodoPago/SDK-Java#17]
Estimados,

En el pom.xml de mi proyecto agregue la dependencia:

		<dependency>
			<groupId>com.ar.todopago</groupId>
			<artifactId>TodoPago</artifactId>
			<version>1.9.0</version>
		</dependency>

Pero cual es la url del repository?

	<repositories>
		<repository>
			<id>todopago</id>
			<url>XXX</url>
		</repository>
	</repositories>

**Comment by curcio79** [comment]
@gustavofilippini perdon la tardanza en la respuesta, la URL seria
    
http://nexus.redb.ee/content/repositories/TodoPago/

Saludos
