### ISSUE TITLE
Cuenta de vendedor invalida(702)

### ISSUE THREAD

**Issue by SergioDosSantos** [TodoPago/SDK-Java#18]
No importa cuánto regenere el merchant id de test siempre me tira el mismo error, Cuenta de vendedor invalida(702), las integraciones estaban funcionando en test y producción, de repente dejo de funcionar test, cambio algo en el ambiente de test?
Algo que noto es que antes me generaba un Merchant ID diferente al de producción para test y ahora me está entregando el mismo, sólo varía la api key.

**Comment by curcio79** [comment]
@SergioDosSantos buenos dias y perdon por la tardanza, pudiste solucionarlo?

**Comment by SergioDosSantos** [comment]
No, sigue igual, en producción la integración funciona perfecto. Pero nos quedamos sin test.

**Comment by curcio79** [comment]
@SergioDosSantos me pasas tus datos asi verificamos la cuenta? si queres pasamela por mail a ccurcio@primamp.com. Saludos

**Comment by curcio79** [comment]
@SergioDosSantos buenos dias, era un problema en el codigo cuando apuntaba al ambiente de test. En las proximas semanas subimos el error corregido. Muchas gracias por el reporte. Saludos
