### ISSUE TITLE
Error: 400 - Bad Request al confirmar formulario de Pago

### ISSUE THREAD

**Issue by Lukafocus** [TodoPago/SDK-Java#19]
Estimados, 
Luego de ejecutar el tpc.sendAuthorizeRequest, y redireccionarme correctamente  al formulario de Pago, al confirmar el mismo me esta devolviendo el siguiente error:

Error: 400 - Bad Request - <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

finalmente me redicrecciona a la URL_ERROR.

En el portal de TP queda registrado el rechazo, pero en la tarjeta de crédito se genera el consumo.

Dato adicional: Tengo varias implementaciones de la misma aplicación, y con otros clientes no he tenido inconvenientes.

Se agradecen ideas y sugerencias.

**Comment by curcio79** [comment]
@Lukafocus es probable que te este faltando alguna informacion requerida. Si no lo solucionaste y queres verlo conmigo, Genera un nuevo issue y lo resolvemos. Saludos
