### ISSUE TITLE
Compilar librería TodoPago.jar a java 1.7

### ISSUE THREAD

**Issue by ntoirac** [TodoPago/SDK-Java#3]
Estimados:

Estamos teniendo dificultad al conectarnos con los webservices de la plataforma Todo Pago por medio de la librería TodoPago.jar, específicamente el componente TodoPagoConector, método: SendAuthorizeRequest . El error que nos está arrojando es el siguiente:

[org.apache.cxf.phase.PhaseInterceptorChain] (http-/172.18.12.68:8080-3) Interceptor for {http://api.todopago.com.ar}Authorize#{http://api.todopago.com.ar}SendAuthorizeRequest has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: Unmarshalling Error: unexpected element (uri:"http://api.todopago.com.ar", local:"Channel"). Expected elements are <{http://api.todopago.com.ar}StatusMessage>,<{http://api.todopago.com.ar}RequestKey>,<{http://api.todopago.com.ar}URL_Request>,<{http://api.todopago.com.ar}StatusCode>,<{http://api.todopago.com.ar}PublicRequestKey> 

Analizando este error, nos dimos cuenta que el manifiesto de la libraría TodoPago.jar especifica que fue compilada para la version 1.8 de java. Esto es posible que sea la causa del anterior error comentado.

Nos podrían facilitar una libraría compilada para la version 1.7 de java.

MANIFEST.MF:

Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Built-By: juan.peregrina
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_92

**Comment by gabiperegrina** [comment]
La ultima versión 1.4.1 esta buildiada en Java 1.5 , Saludos.

**Comment by gabiperegrina** [comment]
Apuntando a developer tira el mismo error?

**Comment by ntoirac** [comment]
Sí!!!!

**Comment by ntoirac** [comment]
Estimados, este es el endpoint cuando estoy justo de enviar el SendAuthorizeRequest : 
https://developers.todopago.com.ar/services/t/1.1/Authorize

Favor confirmarnos si es el corecto?

**Comment by ntoirac** [comment]
Log al enviar el SendAuthorizeRequest (Clase: TodoPagoConectorAuthorize) :

09:10:58,195 INFO  [stdout] (http-/172.18.12.68:8080-2) Wed Jun 08 09:10:58 ART 2016: Operacion: o95600083_0, sendAuthorizeRequest:parameters: {Security=2edca36520784e9884f26a79bc078854, URL_OK=http://172.18.12.68:8080/ribeiro/test/okTodoPago.jsp?Order=o95600083_0, Amount=200.00, EMAILCLIENTE=ecommerce@ribeiro.com.ar, URL_ERROR=http://172.18.12.68:8080/ribeiro/test/errorTodoPago.jsp?Order=o95600083_0, EncodingMethod=XML, Merchant=2542, Session=ABCDEF-1234-12221-FDE1-00000200, OperationId=o95600083_0, CurrencyCode=032}

09:12:28,597 INFO  [ar.com.todopago.utils.TodoPagoConectorAuthorize] (http-/172.18.12.68:8080-2) Armando payload: <Request><SECURITY>2edca36520784e9884f26a79bc078854</SECURITY><URL_OK>http://172.18.12.68:8080/ribeiro/test/okTodoPago.jsp?Order=o95600083_0</URL_OK><AMOUNT>200.00</AMOUNT><EMAILCLIENTE>ecommerce@ribeiro.com.ar</EMAILCLIENTE><URL_ERROR>http://172.18.12.68:8080/ribeiro/test/errorTodoPago.jsp?Order=o95600083_0</URL_ERROR><ENCODINGMETHOD>XML</ENCODINGMETHOD><MERCHANT>2542</MERCHANT><SESSION>ABCDEF-1234-12221-FDE1-00000200</SESSION><OPERATIONID>o95600083_0</OPERATIONID><CURRENCYCODE>032</CURRENCYCODE><CSSTLASTNAME>Perez Destinatario</CSSTLASTNAME><CSMDD9></CSMDD9><CSBTFIRSTNAME>Nerius Destinatario</CSBTFIRSTNAME><CSMDD6></CSMDD6><CSBTCITY>Ciudad Autonoma de Buenos Aires</CSBTCITY><CSMDD8>N</CSMDD8><CSMDD7></CSMDD7><CSITPRODUCTCODE>01000101011</CSITPRODUCTCODE><CSSTPHONENUMBER>1159104553</CSSTPHONENUMBER><CSBTCUSTOMERID>100358893</CSBTCUSTOMERID><CSSTSTATE>C</CSSTSTATE><CSBTEMAIL>suirennerius1982@gmail.com</CSBTEMAIL><CSPTCURRENCY>ARS</CSPTCURRENCY><CSITTOTALAMOUNT>200.00</CSITTOTALAMOUNT><CSSTPOSTALCODE>C1010AAP</CSSTPOSTALCODE><CSBTSTATE>C</CSBTSTATE><CSITQUANTITY>0</CSITQUANTITY><CSBTLASTNAME>Perez Destinatario</CSBTLASTNAME><CSPTGRANDTOTALAMOUNT>200.00</CSPTGRANDTOTALAMOUNT><CSMDD10></CSMDD10><CSMDD11></CSMDD11><CSMDD12></CSMDD12><CSMDD13></CSMDD13><CSBTCOUNTRY>AR</CSBTCOUNTRY><CSMDD14>N</CSMDD14><CSMDD15></CSMDD15><CSMDD16></CSMDD16><CSSTEMAIL>suirennerius1982@gmail.com</CSSTEMAIL><CSBTSTREET1>Yerbal 1000</CSBTSTREET1><CSBTIPADDRESS>172.18.12.66</CSBTIPADDRESS><CSBTPHONENUMBER>1159104553</CSBTPHONENUMBER><CSBTPOSTALCODE>C1010AAP</CSBTPOSTALCODE><CSITPRODUCTDESCRIPTION>Description product</CSITPRODUCTDESCRIPTION><CSITUNITPRICE>0.00</CSITUNITPRICE><CSSTCOUNTRY>AR</CSSTCOUNTRY><CSSTCITY>Ciudad Autonoma de Buenos Aires</CSSTCITY><CSSTSTREET1>Yerbal 1000</CSSTSTREET1><CSSTFIRSTNAME>Nerius Destinatario</CSSTFIRSTNAME><CSITPRODUCTNAME>Product name</CSITPRODUCTNAME><CSITPRODUCTSKU>88999</CSITPRODUCTSKU></Request>
09:12:28,615 INFO  [ar.com.todopago.utils.TodoPagoConectorAuthorize] (http-/172.18.12.68:8080-2) Armando SendAuthorizeRequest: ar.com.todopago.api.authorize.SendAuthorizeRequest@6d8b84e4
09:12:34,803 WARNING [org.apache.cxf.phase.PhaseInterceptorChain] (http-/172.18.12.68:8080-2) Interceptor for {http://api.todopago.com.ar}Authorize#{http://api.todopago.com.ar}SendAuthorizeRequest has thrown exception, unwinding now: org.apache.cxf.interceptor.Fault: Unmarshalling Error: unexpected element (uri:"http://api.todopago.com.ar", local:"Channel"). Expected elements are <{http://api.todopago.com.ar}StatusMessage>,<{http://api.todopago.com.ar}RequestKey>,<{http://api.todopago.com.ar}URL_Request>,<{http://api.todopago.com.ar}StatusCode>,<{http://api.todopago.com.ar}PublicRequestKey> 
	at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:808)
	at org.apache.cxf.jaxb.JAXBEncoderDecoder.unmarshall(JAXBEncoderDecoder.java:629)
	at org.apache.cxf.jaxb.io.DataReaderImpl.read(DataReaderImpl.java:157)
	at org.apache.cxf.interceptor.DocLiteralInInterceptor.handleMessage(DocLiteralInInterceptor.java:203)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:262)
	at org.apache.cxf.endpoint.ClientImpl.onMessage(ClientImpl.java:800)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1696)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1532)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1440)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:659)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:262)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:463)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:366)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:319)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:134)
	at com.sun.proxy.$Proxy74.sendAuthorizeRequest(Unknown Source)
	at ar.com.todopago.utils.TodoPagoConectorAuthorize.getpaymentValues(TodoPagoConectorAuthorize.java:82) [TodoPago.jar:]
	at ar.com.todopago.api.TodoPagoConector.sendAuthorizeRequest(TodoPagoConector.java:106) [TodoPago.jar:]

**Comment by damianwajser** [comment]
Estimados, 
Esto es un cambio que tenemos que realizar en la plataforma, se cambio la firma del servicio se esta reviriyendo el cambio.

**Comment by ntoirac** [comment]
Estimado, tienen estimado para cuando estará listo, así continuamos con las pruebas?

Favor avisarnos en cuanto hayan hecho los ajustes, así continuamos con esta parte.

**Comment by damianwajser** [comment]
Por favor me avisan si siguen con el inconveniente. 
deberia estar solucionado.
Gracias.

**Comment by ntoirac** [comment]
Estimado, muchas gracias por el aviso.

Recién estamos probando, hasta el momento nos funcionó el sendAuthRequest, ahora continuamos con las otras pruebas.

Les mantenemos al tanto según los resultados.

Saludos!!!
