### ISSUE TITLE
Consulta sobre PEI: Pago Electrónico Inmediato

### ISSUE THREAD

**Issue by ntoirac** [TodoPago/SDK-Java#7]
Estimados:
Le escribo desde la firma Ribeiro, cliente de uds.
Nos pueden suministrar información técnica referida a pago por PEI. Ver adjunto.
[Todo Pago PEI.pdf](https://github.com/TodoPago/SDK-Java/files/917254/Todo.Pago.PEI.pdf)

**Comment by precagno** [comment]
No es posible utilizar PEI en desarrollo.Saludos
