### ISSUE TITLE
StatusCode=999, PublicRequestKey=, URL_Request=, StatusMessage=ERROR: Internal Error, RequestKey=}

### ISSUE THREAD

**Issue by lucianofedericoolmedo** [TodoPago/SDK-Java#8]
Hola muchachos, una consulta, durante 6 meses estuvimos usando su API de desarrollo (para developers, no prod) con resultados satisfactorios con credenciales similares a  las de https://github.com/TodoPago/SDK-Java pero desde hace un par de dias, al momento de iniciar un tpc.sendAuthorizeRequest(parameters, getFraudControlParameters());  obtengo
un {StatusCode=999, PublicRequestKey=, URL_Request=, StatusMessage=ERROR: Internal Error, RequestKey=}, busque info acerca de el posible error sin mayor suerte. 
Desde ya muchas gracias...
Les paso parte del trace:

Jul 11, 2017 12:06:00 PM ar.com.todopago.utils.TodoPagoConectorAuthorize createPayload
INFO: Armando payload: <Request><OPERATIONID>8000</OPERATIONID><SECURITY>1234567890ABCDEF1234567890ABCDEF</SECURITY><URL_OK>http,//someurl.com/ok/</URL_OK><AMOUNT>1.00</AMOUNT><EMAILCLIENTE>some@someurl.com</EMAILCLIENTE><URL_ERROR>http,//someurl/fail/</URL_ERROR><ENCODINGMETHOD>XML</ENCODINGMETHOD><MERCHANT>12345678</MERCHANT><SESSION>ABCDEF-1234-12221-FDE1-00000200</SESSION><CURRENCYCODE>032</CURRENCYCODE><CSSTLASTNAME>Perez</CSSTLASTNAME><CSMDD9></CSMDD9><CSBTFIRSTNAME>Juan</CSBTFIRSTNAME><CSBTCITY>Villa General Belgrano</CSBTCITY><CSMDD8>N</CSMDD8><CSMDD7></CSMDD7><CSITPRODUCTCODE>electronic_good</CSITPRODUCTCODE><CSSTPHONENUMBER>541160913988</CSSTPHONENUMBER><CSBTCUSTOMERID>453458</CSBTCUSTOMERID><CSSTSTATE>B</CSSTSTATE><CSPTCURRENCY>ARS</CSPTCURRENCY><CSBTEMAIL>some@someurl.com</CSBTEMAIL><CSITTOTALAMOUNT>10.01</CSITTOTALAMOUNT><CSSTPOSTALCODE>1010</CSSTPOSTALCODE><CSBTSTATE>B</CSBTSTATE><CSITQUANTITY>1</CSITQUANTITY><CSBTLASTNAME>Perez</CSBTLASTNAME><CSPTGRANDTOTALAMOUNT>125.38</CSPTGRANDTOTALAMOUNT><CSMDD10></CSMDD10><CSMDD11></CSMDD11><CSMDD12></CSMDD12><CSMDD13></CSMDD13><CSBTCOUNTRY>AR</CSBTCOUNTRY><CSMDD14>N</CSMDD14><CSMDD15></CSMDD15><CSMDD16></CSMDD16><CSBTSTREET2>Piso 8</CSBTSTREET2><CSSTEMAIL>some@someurl.com</CSSTEMAIL><CSBTSTREET1>Some Street 2153</CSBTSTREET1><CSBTIPADDRESS>192.0.0.4</CSBTIPADDRESS><CSBTPHONENUMBER>541160913988</CSBTPHONENUMBER><CSBTPOSTALCODE>1010</CSBTPOSTALCODE><CSITPRODUCTDESCRIPTION>Test Prd Description</CSITPRODUCTDESCRIPTION><CSITUNITPRICE>10.01</CSITUNITPRICE><CSSTSTREET2>Piso 8</CSSTSTREET2><CSSTCOUNTRY>AR</CSSTCOUNTRY><CSSTCITY>Villa General Belgrano</CSSTCITY><CSSTSTREET1>Some Street 2153</CSSTSTREET1><CSSTFIRSTNAME>Juan</CSSTFIRSTNAME><CSITPRODUCTNAME>TestPrd</CSITPRODUCTNAME><CSITPRODUCTSKU>SKU1234</CSITPRODUCTSKU></Request>
Jul 11, 2017 12:06:00 PM ar.com.todopago.utils.TodoPagoConectorAuthorize parseToSendAuthorizeRequest
INFO: Armando SendAuthorizeRequest: ar.com.todopago.api.authorize.SendAuthorizeRequest@5f662c5
Jul 11, 2017 12:06:00 PM ar.com.todopago.utils.TodoPagoConectorAuthorize parseSendAuthorizeRequestResponseToArray
INFO: Armando sendAuthorizeRequestResponse: {StatusCode=999, PublicRequestKey=, URL_Request=, StatusMessage=ERROR: Internal Error, RequestKey=}
{StatusCode=999, PublicRequestKey=, URL_Request=, StatusMessage=ERROR: Internal Error, RequestKey=}

**Comment by lucianofedericoolmedo** [comment]
Me falto aclarar que es con la version 1.5.0 con la que estoy trabajando.
Saludos

**Comment by precagno** [comment]
Probablemente sea un error de conexión al momento de realizar el SAR.De todos modos hace poco se subió una versión nueva de la sdk.Saludos
