### ISSUE TITLE
Error en la pagina de bienvenida https://github.com/TodoPago/SDK-Java

### ISSUE THREAD

**Issue by bardackx** [TodoPago/SDK-Java#9]
Parece que hubo un deslíz de dedo
En la primer linea de código en la sección de uso escriben:

`Map<String, List<String>> auth = new HashMap<>(String, List<String>);`

Y debería ser

`Map<String, List<String>> auth = new HashMap<String, List<String>>();`

**Comment by precagno** [comment]
Buen día.

Gracias por la correción.
